# Generated by Django 2.0.2 on 2018-02-08 02:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, verbose_name='Invitation code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_invited', models.DateTimeField(default=datetime.datetime.now, verbose_name='date invited')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitor')),
            ],
            options={
                'verbose_name': 'Invitation',
                'ordering': ('-date_invited',),
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='InvitationUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=0, verbose_name='available invitations')),
                ('sent', models.IntegerField(default=0, verbose_name='invitations sent')),
                ('accepted', models.IntegerField(default=0, verbose_name='invitations accepted')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_use', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
            ],
        ),
    ]
